const Router = require("@koa/router")
const router = new Router()

const  shopInfoRouter = require("./shopinfo.routes")
const UserRouter = require("./user.routes")
const adsRouter = require("./adsmanagement.routes")
const bikeCategoryRouter = require("./bikecategory.routes")
const bikeInfoRouter = require("./bikeinfo.routes")
const ClientRouter = require("./client.routes")
const paymentRouter = require("./payment.routes")
const penaltyRouter = require("./penalty.routes")
const rentalRouter = require("./rental.routes")
const usergroupRouter = require("./usergroup.routes")
const tokenRouter = require("./token.routes")
const otpRouter = require("./otp.routes")
const responses = require("./responses.routes")

router.use(responses())

router.use("/api/shopinfo",shopInfoRouter())
router.use("/api/user",UserRouter())
router.use("/api/ads",adsRouter())
router.use("/api/bikecategory",bikeCategoryRouter())
router.use("/api/info",bikeInfoRouter())
router.use("/api/client",ClientRouter())
router.use("/api/payment",paymentRouter())
router.use("/api/penalty",penaltyRouter())
router.use("/api/rental",rentalRouter())
router.use("/api/usergroup",usergroupRouter())
router.use("/api/token",tokenRouter())
router.use("/api/otp",otpRouter())

module.exports = router.routes()
